### PR TITLE
fix: don't add count if already in query

### LINKED ISSUE #4: Search export breaks if I export a search with a `count: ` filter
In the network request, it looks like we attach a count:999999 to the extension graphql search results request, which understandably breaks it if I already have a count (you can’t have two “count” filters).

We should handle this by only attaching the count:999999999 if a user doesn't pass a count.

### PR DESCRIPTION
**Pull request by tjkandala**
Fix #4.

### CODE REVIEW

File: src/util.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
+const countPrefix = 'count:'
+/**
+ * Returns whether the query specifies a count. Search queries break when count is specified twice.
+ */
+export function queryHasCount(query: string): boolean {
```
Comment (muratsu) [inline src/util.ts:5]: This would break for search queries where count is escaped:

https://sourcegraph.com/search?q=context:global+%22count:10%22&patternType=literal

Comment (tjkandala) [reply src/util.ts:5]: I don't think it would, check the newly added test case. This function checks any whitespaced-separated component starts with `count:`, which it wouldn't if it's quoted. We [can still use](https://sourcegraph.com/search?q=context:global+%22count:10%22+count:2&patternType=literal) the `count` filter type on top of that, so it should return `false`:

Comment (muratsu) [reply src/util.ts:5]: Right, my point was that just splitting is not enough. "foo count:4 " will not work in this case. The search team must have a more complicated regex parser that we can use.
